package TableExampleLang.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Child1 = 0;
  public static final int Child2 = 1;
  public static final int ExternalItem = 2;
  public static final int Root = 3;
  public static final int UsesItem = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xc138eb89f4c94197L, 0x9e50c9be86419d33L);
    builder.put(0x169a53a412f2def3L, Child1);
    builder.put(0x169a53a412f2def4L, Child2);
    builder.put(0x169a53a412f741a9L, ExternalItem);
    builder.put(0x169a53a412f2def2L, Root);
    builder.put(0x169a53a412f741acL, UsesItem);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
