package TableExampleLang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptChild1 = createDescriptorForChild1();
  /*package*/ final ConceptDescriptor myConceptChild2 = createDescriptorForChild2();
  /*package*/ final ConceptDescriptor myConceptExternalItem = createDescriptorForExternalItem();
  /*package*/ final ConceptDescriptor myConceptRoot = createDescriptorForRoot();
  /*package*/ final ConceptDescriptor myConceptUsesItem = createDescriptorForUsesItem();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptChild1, myConceptChild2, myConceptExternalItem, myConceptRoot, myConceptUsesItem);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Child1:
        return myConceptChild1;
      case LanguageConceptSwitch.Child2:
        return myConceptChild2;
      case LanguageConceptSwitch.ExternalItem:
        return myConceptExternalItem;
      case LanguageConceptSwitch.Root:
        return myConceptRoot;
      case LanguageConceptSwitch.UsesItem:
        return myConceptUsesItem;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForChild1() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TableExampleLang", "Child1", 0xc138eb89f4c94197L, 0x9e50c9be86419d33L, 0x169a53a412f2def3L);
    b.class_(false, false, false);
    b.origin("r:5c7b9581-2d70-4f55-9dd8-481523a6cef2(TableExampleLang.structure)/1628706179405504243");
    b.version(2);
    b.property("c1Property1", 0x169a53a412f2defbL).type(PrimitiveTypeId.STRING).origin("1628706179405504251").done();
    b.property("c2Properrty2", 0x169a53a412f2defdL).type(PrimitiveTypeId.STRING).origin("1628706179405504253").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForChild2() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TableExampleLang", "Child2", 0xc138eb89f4c94197L, 0x9e50c9be86419d33L, 0x169a53a412f2def4L);
    b.class_(false, false, false);
    b.origin("r:5c7b9581-2d70-4f55-9dd8-481523a6cef2(TableExampleLang.structure)/1628706179405504244");
    b.version(2);
    b.property("c2Property1", 0x169a53a412f2df00L).type(PrimitiveTypeId.STRING).origin("1628706179405504256").done();
    b.property("c2Property2", 0x169a53a412f2df02L).type(PrimitiveTypeId.STRING).origin("1628706179405504258").done();
    b.aggregate("usesItem", 0x169a53a412f741f5L).target(0xc138eb89f4c94197L, 0x9e50c9be86419d33L, 0x169a53a412f741acL).optional(true).ordered(true).multiple(true).origin("1628706179405791733").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForExternalItem() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TableExampleLang", "ExternalItem", 0xc138eb89f4c94197L, 0x9e50c9be86419d33L, 0x169a53a412f741a9L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:5c7b9581-2d70-4f55-9dd8-481523a6cef2(TableExampleLang.structure)/1628706179405791657");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRoot() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TableExampleLang", "Root", 0xc138eb89f4c94197L, 0x9e50c9be86419d33L, 0x169a53a412f2def2L);
    b.class_(false, false, true);
    b.origin("r:5c7b9581-2d70-4f55-9dd8-481523a6cef2(TableExampleLang.structure)/1628706179405504242");
    b.version(2);
    b.aggregate("children1", 0x169a53a412f2def6L).target(0xc138eb89f4c94197L, 0x9e50c9be86419d33L, 0x169a53a412f2def3L).optional(true).ordered(true).multiple(true).origin("1628706179405504246").done();
    b.aggregate("children2", 0x169a53a412f2def8L).target(0xc138eb89f4c94197L, 0x9e50c9be86419d33L, 0x169a53a412f2def4L).optional(true).ordered(true).multiple(true).origin("1628706179405504248").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForUsesItem() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TableExampleLang", "UsesItem", 0xc138eb89f4c94197L, 0x9e50c9be86419d33L, 0x169a53a412f741acL);
    b.class_(false, false, false);
    b.origin("r:5c7b9581-2d70-4f55-9dd8-481523a6cef2(TableExampleLang.structure)/1628706179405791660");
    b.version(2);
    b.associate("item", 0x169a53a412f741afL).target(0xc138eb89f4c94197L, 0x9e50c9be86419d33L, 0x169a53a412f741a9L).optional(false).origin("1628706179405791663").done();
    return b.create();
  }
}
