package TableExampleLang.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Child1_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Child2_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Root_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new UsesItem_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new UsesItem_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xc138eb89f4c94197L, 0x9e50c9be86419d33L, 0x169a53a412f2def3L), MetaIdFactory.conceptId(0xc138eb89f4c94197L, 0x9e50c9be86419d33L, 0x169a53a412f2def4L), MetaIdFactory.conceptId(0xc138eb89f4c94197L, 0x9e50c9be86419d33L, 0x169a53a412f2def2L), MetaIdFactory.conceptId(0xc138eb89f4c94197L, 0x9e50c9be86419d33L, 0x169a53a412f741acL)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xc138eb89f4c94197L, 0x9e50c9be86419d33L, 0x169a53a412f741acL)).seal();
}
